# Generated by Django 5.1.3 on 2024-11-27 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_lesson_courses'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateTimeField(blank=True, null=True, verbose_name='дата оплаты')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма оплаты')),
                ('payment_type', models.CharField(choices=[('наличные', 'наличные'), ('безналичный', 'безналичный')], default='безналичный', max_length=11)),
                ('payment_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='materials.course', verbose_name='оплаченный курс')),
                ('payment_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.lesson', verbose_name='оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
