# Generated by Django 5.1.3 on 2025-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="url"),
        ),
    ]
